/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;

import java.awt.Color;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;

/**
 *
 * @author mario
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setSize(300, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        dibujar = new javax.swing.JButton();
        color = new javax.swing.JButton();
        relleno = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        formas = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        lienzo = new test.lienzo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        dibujar.setText("Dibujar");
        dibujar.setFocusable(false);
        dibujar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dibujar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dibujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dibujarActionPerformed(evt);
            }
        });
        jToolBar1.add(dibujar);

        color.setText("Color");
        color.setFocusable(false);
        color.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        color.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });
        jToolBar1.add(color);

        relleno.setText("Relleno");
        relleno.setFocusable(false);
        relleno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        relleno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        relleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rellenoActionPerformed(evt);
            }
        });
        jToolBar1.add(relleno);

        jButton4.setText("Imagen");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        formas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Linea", "Elipse", "Rectangulo", "Trazo Libre" }));
        formas.setMaximumSize(new java.awt.Dimension(110, 24));
        jToolBar1.add(formas);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setMaximumSize(new java.awt.Dimension(110, 24));
        jComboBox1.setMinimumSize(new java.awt.Dimension(110, 24));
        jComboBox1.setPreferredSize(new java.awt.Dimension(110, 24));
        jToolBar1.add(jComboBox1);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Shape setForma(){
        switch(formas.getSelectedIndex()){
            case 0:
                lienzo.setTrazado(false);
                return new Line2D.Float(100,100,200,200);
            
            case 1:
                lienzo.setTrazado(false);
                return new Ellipse2D.Float(100, 100, 50, 50);
               
            case 2:
                lienzo.setTrazado(false);
                return new Rectangle2D.Float(100,100,50,50);
                
            case 3:
                lienzo.setTrazado(true);
                break;
        }
        
        return new Line2D.Float(0,0,1,1);
    }
    
    private void dibujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dibujarActionPerformed
        Shape s = setForma();
        lienzo.setShape(s);
        lienzo.repaint();
    }//GEN-LAST:event_dibujarActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        Color color = JColorChooser.showDialog(this, "Elige un color", Color.black);
        lienzo.setColor(color);
    }//GEN-LAST:event_colorActionPerformed

    private void rellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rellenoActionPerformed
        lienzo.setRelleno(!lienzo.getRelleno());
    }//GEN-LAST:event_rellenoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        
        if (resp == JFileChooser.APPROVE_OPTION){
            try{
                File f = dlg.getSelectedFile();
                BufferedImage img = ImageIO.read(f);
                
                lienzo.setImage(img);
            }
            
            catch(Exception e){
                System.err.println("Error al abrir la imagen");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton color;
    private javax.swing.JButton dibujar;
    private javax.swing.JComboBox<String> formas;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JToolBar jToolBar1;
    private test.lienzo lienzo;
    private javax.swing.JButton relleno;
    // End of variables declaration//GEN-END:variables
}
